# Generated by Django 5.0.9 on 2024-12-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/Blues_logo.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
