# Generated by Django 5.0.9 on 2024-12-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="review_request_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
