# Generated by Django 5.0.9 on 2024-11-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=99, upload_to="images/"),
            preserve_default=False,
        ),
    ]
