# Generated by Django 5.0.9 on 2024-11-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
