# Generated by Django 5.0.9 on 2024-11-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="empty", upload_to="", verbose_name="{name}_title.jpg"
            ),
            preserve_default=False,
        ),
    ]
