<<<<<<< HEAD
# Generated by Django 5.0.9 on 2024-11-26 19:11
=======
# Generated by Django 5.0.9 on 2024-11-26 18:09
>>>>>>> 251cee785c7b28a380996857f7c8a4bfdc42850a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("products", "0003_product_image"),
=======
        ('products', '0003_product_image'),
>>>>>>> 251cee785c7b28a380996857f7c8a4bfdc42850a
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
=======
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
>>>>>>> 251cee785c7b28a380996857f7c8a4bfdc42850a
        ),
    ]
