# Generated by Django 5.0.9 on 2024-12-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
        ('products', '0004_alter_product_image'),
    ]

    operations = [
    ]
